version: '2'
services:
  life360-cassandra:
    image: tobert/cassandra:2.1.3
    ports:
      - "9042:9042"
      - "9160:9160"
  rgcmap:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - life360-cassandra
    links:
      - life360-cassandra
    command: rgcmap -d life360-cassandra
