version: '2'
services:
  rgcmap:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - life360-cassandra
  life360-cassandra:
    image: tobert/cassandra:2.1.3
    ports:
      - "9042:9042"
      - "9160:9160"
